version: "3.7"

services:
    web:
        build: ./web
        ports:
            - "5000:5000" 
        links:
            - db
        environment:
            - FLASK_DEBUG=1
            - FLASK_ENV=development
            - FLASK_APP=app.py
        # volumes: [./web/app]
    db:
        build: ./db